apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: saleor-load
  namespace: {{ .Namespace }}
spec:
  parallelism: 2
  script:
    configMap:
      name: test-script
      file: test.js
  runner:
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "k6"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - load-generator
    env:
      - name: TARGET_DOMAIN
        value: "{{ .Target }}"
